#!/usr/bin/env bash

export PYTHONWARNINGS="ignore::DeprecationWarning"

hook_dir="$(dirname "${BASH_SOURCE[0]}")"
scripts_dir="${hook_dir}/scripts"

function run_clang_format_diff() {
    echo "Running clang-format-diff..."

    local fmt_diff=$(git diff --no-ext-diff -U0 --no-color --relative --cached | ${scripts_dir}/clang-format-diff.py -p1)

    local colorize_diff='
        /^+/ { printf "\033[1;32m" }
        /^-/ { printf "\033[1;31m" }
        // { print $0 "\033[0m"; }'

    if [[ -n ${fmt_diff} ]]; then
        echo "${fmt_diff}" | awk "${colorize_diff}"
        echo -e "\nPlease re-format above files before commit"
        exit 1
    fi

    echo "clang-format-diff passed"
}

function run_cpplint_check() {
    echo "Running cpplint check..."

    local changed_files=$(git diff --cached --name-only | grep -iE '\.(cpp|cc|c|hpp|hh|h)$')
    if [[ -n ${changed_files} ]]; then
        ${scripts_dir}/cpplint.py --quiet ${changed_files}
        if [[ "$?" -ne 0 ]]; then
            exit 1
        fi
    fi

    echo "cpplint check passed"
}

function detect_cxx_compiler() {
    local cxx="/usr/bin/c++"
    local macros=$(printf '' | "$cxx" -dM -E - 2>/dev/null || true)

    if [[ $macros == *"#define __clang__"* ]]; then
        printf 'clang'
    elif [[ $macros == *"#define __GNUC__"* ]]; then
        printf 'gcc'
    else
        printf 'unknown'
    fi
}

function run_clang_tidy_diff() {
    echo "Running clang-tidy-diff..."

    local compile_db_dir="out"
    local src_compile_db="${compile_db_dir}/compile_commands.json"

    if [[ ! -f ${src_compile_db} ]]; then
        echo "${src_compile_db} not found, skip clang-tidy-diff"
        exit 0
    fi

    git diff --no-ext-diff -U0 --cached | \
        ${scripts_dir}/clang-tidy-diff.py -p1 \
                                          -use-color \
                                          -only-check-in-db \
                                          -extra-arg=-Wno-unknown-warning-option \
                                          -path ${compile_db_dir} \
                                          -j $(($(nproc) / 2 + 1))
    if [[ "$?" -ne 0 ]]; then
        exit 1
    fi
    echo "clang-tidy-diff passed"
}

run_clang_format_diff && \
run_cpplint_check && \
run_clang_tidy_diff
